resources:
- namespace.yaml
- ../base
namespace: api-service
transformers:
- metadata-label-transformer.yaml
patchesStrategicMerge:
- replica-count.yaml
- resource.yaml
- env-var.yaml
- labels.yaml
- nodeselector.yaml
images:
- name: spring-kotlin-server
  newName: [azure container registry name].azurecr.io/dev-spring-kotlin-server
  newTag: 3edf6f996166947e9e1afb7c9c08119bcfbf6897
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: ingress-patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: main-service-ingress
    version: v1
