apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: spring-kotlin-server-hpa
  namespace: main-api-service
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-kotlin-server
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
---
