resources:
- namespace.yaml
- ../base
- pod-auto-scaler.yaml
namespace: main-api-service
transformers:
- metadata-label-transformer.yaml
patchesStrategicMerge:
- replica-count.yaml
- resource.yaml
- env-var.yaml
- labels.yaml
- nodeselector.yaml
images:
- name: spring-kotlin-server
  newName: [azure container registry name].azurecr.io/dev-spring-kotlin-server
  newTag: c6a80793c00d14059b388f4ca09d902ad92f94d2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: ingress-patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: main-service-ingress
    version: v1