apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-kotlin-server
spec:
  template:
    spec:
      containers:
        - name: api
          resources:
            requests:
              cpu: 1000m
              memory: 1000Mi
            limits:
              cpu: 1100m
